tss_netmgr: fix bugs, add LACP bonding support

diff --git a/scripts/tss_netmgr b/scripts/tss_netmgr
--- a/scripts/tss_netmgr
+++ b/scripts/tss_netmgr
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-VER=0.2.1
-VERDATE=2014-09-16
+VER=0.3
+VERDATE=2015-02-16
 
 # When started, collect information about current interface states
 # Attempt to locate a configuration file
@@ -11,8 +11,123 @@ VERDATE=2014-09-16
 SYSNET=/sys/class/net
 WPA_CONF=/etc/wpa.conf
 
-turn_on_link () {
+link_up () {
 	ip link set up dev $1 2>/dev/null >/dev/null
+}
+
+link_down () {
+	ip link set down dev $1 2>/dev/null >/dev/null
+}
+
+flush_ip () {
+	ip addr flush dev $1 2>/dev/null >/dev/null
+}
+
+flush_all_interfaces () {
+	# Terminate IP configuration for all network interfaces
+	# unmount any CIFS filesystems before possibly disconnecting things
+	umount -f $(cat /proc/mounts | grep '[^ ]* [^ ]* cifs' | cut -d' ' -f2) 2>/dev/null
+	killall -q udhcpc
+	killall -q wpa_supplicant
+	sleep 0.3
+	killall -q -9 udhcpc
+	killall -q -9 wpa_supplicant
+	for FLUSH in $SYSNET/*
+		do flush_ip $(basename $FLUSH)
+	done
+	unset IF_INET IF_INET_IP
+}
+
+select_bond_interfaces () {
+	unset BOND_IFACES B_IFACE
+	echo "Select interfaces for LACP bonding"
+	echo "   (Speed and duplex must match)"
+	echo "----------------------------------"
+	NUM=1
+	for X in $IFACE_WIRED
+		do
+		link_up $X
+		SPEED=$(cat /sys/class/net/$X/speed)
+		DUPLEX=$(cat /sys/class/net/$X/duplex)
+		echo "$NUM: $X ($SPEED Mbps, $DUPLEX duplex)"
+		NUM=$((NUM + 1))
+	done
+	echo "Type desired interface numbers i.e. '1 2 4' or type 'all'"
+	echo -en "Which interfaces to use (default: all)? "
+	read BI
+	test -z "$BI" && BI=all
+	if [ "$BI" = "all" ]
+		then
+		# Attach all wired interfaces to the LACP bond
+		NUM=$(echo "$IFACE_WIRED" | wc -w)
+		BOND_IFACES="$IFACE_WIRED"
+
+		else
+		# Attach only selected interfaces
+		NUM=$(echo "$BI" | wc -w)
+		if [ $NUM -lt 2 ]
+			then echo "You must specify at least two interfaces. Aborting."
+			return 1
+		fi
+		for X in $BI
+			do NUM=1
+			for Y in $IFACE_WIRED
+				do test "$X" = "$NUM" && BOND_IFACES="$BOND_IFACES $Y"
+				NUM=$((NUM + 1))
+			done
+		done
+	fi
+}
+
+setup_lacp () {
+	# Set up an 802.3ad (LACP) bond interface from $BOND_IFACES
+	ERR=0
+	test -z "$BOND_IFACES" && echo "setup_lacp called with no BOND_IFACES!" && return 1
+	modprobe bonding 2>/dev/null
+	B_IFACE=bond0
+	B_DIR=/sys/class/net/$B_IFACE/bonding
+
+	# Clear any existing bonding configuration
+	link_down $B_IFACE || ERR=1
+	test ! -e $B_DIR/slaves && echo "Cannot set up bonding (no kernel support)." && return 1
+	for X in $(cat $B_DIR/slaves)
+		do
+		link_down $X || ERR=1
+		echo -$X > $B_DIR/slaves || ERR=1
+		if [ "$ERR" = "1" ]
+			then echo "Error removing bond slaves, aborting."
+			return 1
+		fi
+	done
+	if [ "$ERR" = "1" ]
+		then echo "An error occurred during bond configuration."
+		return 1
+	fi
+
+	# Attach slaves to bond interface and enable it
+	echo 802.3ad > $B_DIR/mode || ERR=1
+	echo 0 > $B_DIR/xmit_hash_policy || ERR=1
+	echo 100 > $B_DIR/miimon || ERR=1
+	echo 5 > $B_DIR/lp_interval || ERR=1
+	if [ "$ERR" = "1" ]
+		then echo "An error occurred while setting bond parameters."
+		return 1
+	fi
+	link_down $B_IFACE || ERR=1
+	for X in $BOND_IFACES
+		do
+		link_down $X || ERR=1
+		echo +$X > $B_DIR/slaves || ERR=1
+	done
+	if [ "$ERR" = "1" ]
+		then echo "Could not attach bond slaves: $BOND_IFACES"
+		return 1
+	fi
+	if ! link_up $B_IFACE
+		then echo "Failed to bring the bond interface $B_IFACE online."
+		return 1
+	fi
+	IFACE_WIRED="$B_IFACE"
 }
 
 get_interface_state () {
@@ -22,15 +137,19 @@ get_interface_state () {
 	for X in $INTERFACES
 		do
 		case "$X" in
-			eth*) IFACE_WIRED="$IFACE_WIRED $X"; turn_on_link $X ;;
-			wlan*) IFACE_WIFI="$IFACE_WIFI $X"; turn_on_link $X ;;
-			lo*) IFACE_LO="$IFACE_LO $X"; turn_on_link $X ;;
+			eth*) IFACE_WIRED="$IFACE_WIRED $X"; link_up $X ;;
+			enp*) IFACE_WIRED="$IFACE_WIRED $X"; link_up $X ;;
+			wlan*) IFACE_WIFI="$IFACE_WIFI $X"; link_up $X ;;
+			wlp*) IFACE_WIFI="$IFACE_WIFI $X"; link_up $X ;;
+			lo*) IFACE_LO="$IFACE_LO $X"; link_up $X ;;
 			*) IFACE_OTHER="$IFACE_OTHER $X" ;;
 		esac
+		# Bonding overrides normal wired interfaces
+		test ! -z "$B_IFACE" && IFACE_WIRED="$B_IFACE" && link_up $IFACE_WIRED
 		test "$(cat $SYSNET/$X/carrier 2>/dev/null)" = "1" && IF_CARRIER="$IF_CARRIER $X"
 	done
 	# If a default route exists, assume the dev is the Internet dev
-	IF_INET="$(ip route | grep -m 1 ^default | sed 's/.* dev //g')"
+	IF_INET="$(ip route | grep -m 1 ^default | sed 's/.* dev //g' | tr -d ' ')"
 	test -n "$IF_INET" && IF_INET_IP="$(ip addr show dev $IF_INET | grep -m 1 '    inet' | sed 's#    inet \([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\)/.*#\1#')"
 }
 
@@ -40,24 +159,33 @@ get_wireless_networks () {
 }
 
 setup_local_loopback () {
-	ip link set up dev lo
+	link_up lo
 	ip addr show dev lo | grep -q '^    inet ' || ip addr add 127.0.0.1/8 dev lo
 }
 
 setup_internet_connection () {
 	get_interface_state
+	if [[ ! -z "$IF_INET_IP" && "$1" != "--init" ]]
+		then
+		echo -en "Connected on ${IF_INET}. Clear and reconfigure (y/n)? "
+		read -n 1 RECONF; echo
+		if [ "$RECONF" = "y" ]
+			then
+			echo "Reconfiguring interfaces."
+			unset IF_INET_IP IF_INET
+		fi
+	fi
+	if [ $(echo $IFACE_WIRED | wc -w) -gt 1 ]
+		then echo -en "Multiple wired interfaces. Set up LACP bonding (y/n)? "
+		read -n 1 BOND; echo
+		test "$BOND" = "y" && select_bond_interfaces && setup_lacp && unset IF_INET_IP
+	fi
 	if [ -z "$IF_INET_IP" ]
 		then
-		# unmount any CIFS filesystems before possibly disconnecting things
-		umount -f $(cat /proc/mounts | grep '[^ ]* [^ ]* cifs' | cut -d' ' -f2) 2>/dev/null
-		killall -q udhcpc
-		killall -q wpa_supplicant
-		sleep 0.2
-		killall -q -9 udhcpc
-		killall -q -9 wpa_supplicant
+		flush_all_interfaces
 		get_interface_state
 		for X in $IFACE_WIRED
-			do ip addr flush dev $X
+			do flush_ip $X
 			echo "$IF_CARRIER" | grep -q " $X" && udhcpc -t 3 -n -i $X >/dev/null
 			get_interface_state
 			test ! -z "$IF_INET_IP" && break 2
@@ -65,7 +193,7 @@ setup_internet_connection () {
 		# If wired interfaces don't work, set up wireless connectivity
 		if [[ -z "$IF_INET_IP" && ! -z "$IFACE_WIFI" ]]
 			then for USE in $IFACE_WIFI
-				do ip addr flush dev $USE
+				do flush_ip $USE
 				get_wireless_networks
 				echo -e "\nWireless networks found on interface $USE"
 				echo "-----------------------------------------"
@@ -77,7 +205,7 @@ setup_internet_connection () {
 						CNT=$((CNT + 1))
 						echo "$CNT: ${ESSID[$CNT]}" >&2
 					done
-					echo -en "\nSelect network (enter to skip, x to stop network config): "
+					echo -en "\nSelect network (enter to skip, x to abort): "
 					read N
 					test -z "$N" && break
 					test "$N" = "x" && exit 1
@@ -111,8 +239,9 @@ setup_internet_connection () {
 if [ "$1" = "--init" ]
 	then echo "Initializing network connections."
 	get_interface_state
+	sleep 1
 	get_interface_state
-	sleep 2
+	sleep 3
 fi
 echo "TSS network connection manager $VER ($VERDATE)"
 setup_local_loopback
