tt__disk_prompt: exclude RAID slaves, support mmcblk devices

diff --git a/scripts/tt__disk_prompt b/scripts/tt__disk_prompt
--- a/scripts/tt__disk_prompt
+++ b/scripts/tt__disk_prompt
@@ -1,46 +1,62 @@
 #!/bin/ash
 
-VER="0.2.2"
-VERDATE="2013-12-26"
+VER="0.3"
+VERDATE="2015-10-08"
 
 # Finds all possible hard drives on the system, provides info on each,
 # and prompts which one to use. Aborts if no drives exist or if the
 # user selects an invalid drive.
+
+control_c () {
+	rm -f $DISKS $TMPFILE
+	echo -e "\nAborting due to user termination."
+	exit 1
+}
+
+trap control_c INT TERM HUP ABRT
 
 DISKS=$(mktemp)
 TMPFILE=$(mktemp)
 
 # Verify that a temporary file name was passed to us
 if [ "$1" = "" ]
-  then echo "${0}: no temporary file name given" ; exit 1
-  else if ! echo "$1" | grep -q "/tmp/"
-    then echo "${0}: temp file must be in /tmp"; exit 2
-  fi
+	then echo "${0}: no temporary file name given" ; exit 1
+	else if ! echo "$1" | grep -q "/tmp/"
+		then echo "${0}: temp file must be in /tmp"; exit 2
+	fi
 fi
 
 # Check to ensure there are possible hard drives at all
 # Additionally, determine if we use hdX or sdX drive designations
 cat /proc/partitions | tail -n +3 | \
-  awk '{ print $3" "$4" " }' | grep '[sh]d[a-z] ' | sort -g > $DISKS
+	awk '{ print $3" "$4" " }' | grep '[sh]d[a-z] ' | sort -g > $DISKS
+cat /proc/partitions | tail -n +3 | \
+	awk '{ print $3" "$4" " }' | grep 'mmcblk[0-9]* ' | sort -g >> $DISKS
 if cat $DISKS | grep -qv '[sh]d[a-z] '
-  then echo "No sd or hd disk devices were found." ;
-  exit 3
+	then if cat $DISKS | grep -qv 'mmcblk[0-9]* '
+		then echo "No sd, hd, or mmcblk disk devices were found." ;
+		exit 3
+	fi
 fi
 
+# Load RAID slave devices for RAID device exclusion
+KILL="$(echo /sys/block/md*/slaves/* | tr ' ' '\n' | grep -v '\*' | sed 's#.*/##g;s/\([hs]d[a-z]\)[0-9]*.*/\1/;s/\(mmcblk[0-9]*\).*/\1/' | sort -g | uniq | tr '\n' ' ')"
+
 # Scan sysfs to determine what disks are removable disks
-for X in $(cat $DISKS | awk '{ print $2 }' | tr \\\n " ")
-  do REM=$(cat /sys/block/$X/removable | tr -d \\\n);
-  readlink /sys/block/$X | grep -q "/usb" && USB=1 || USB=0
-  cat $DISKS | sed s/"$X"/"$X $REM $USB"/g > $TMPFILE ; mv $TMPFILE $DISKS
+for X in $(cat $DISKS | awk '{ print $2 }' | tr '\n' " ")
+	do REM=$(cat /sys/block/$X/removable | tr -d '\n');
+	RAID=0; echo "$KILL" | grep "$X" && RAID=1
+	readlink /sys/block/$X | grep -q "/usb" && USB=1 || USB=0
+	cat $DISKS | sed s/"$X"/"$X $REM $USB $RAID"/g > $TMPFILE ; mv $TMPFILE $DISKS
 done
 
 # Try to determine which disk is most likely to be the internal hard drive
-PREF=$(cat $DISKS | grep " 0 0" | head -n 1 | cut -d" " -f 2)
+PREF=$(cat $DISKS | grep " 0 0 0" | head -n 1 | cut -d" " -f 2)
 if [ "$PREF" = "" ]
-  then echo "WARNING: No non-USB and non-removable disks detected."
-  echo "Do not trust that the default device chosen for you is correct!"
-  PREF=$(cat $DISKS | head -n 1 | cut -d" " -f 2)
-  echo "$CYEL$PREF$COFF was chosen as the default out of ALL possible disks."
+	then echo "WARNING: No non-USB, non-removable, non-RAID devices found."
+	echo "DO NOT trust that the default device chosen for you is correct!"
+	PREF=$(cat $DISKS | head -n 1 | cut -d" " -f 2)
+	echo "$CYEL$PREF$COFF was chosen as the default out of ALL possible disks."
 fi
 
 tt_fsinfo nopart
