tt_driverdrop: add a read failure error check

diff --git a/scripts/tt_driverdrop b/scripts/tt_driverdrop
--- a/scripts/tt_driverdrop
+++ b/scripts/tt_driverdrop
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-VER=0.8.1
-VERDATE=2016-10-14
+VER=0.8.2
+VERDATE=2016-10-20
 
 BLACKLIST=" acpi:dev=pnp0103 acpi:dev=pnp0300 acpi:dev=pnp0301 acpi:dev=pnp0302 acpi:dev=pnp0303 acpi:dev=pnp0a03 acpi:dev=pnp0a08 acpi:dev=pnp0c0f acpi:dev=abcd0001 acpi:dev=int3f0d"
 
@@ -209,7 +209,10 @@ fi
 echo -n "${CWHT}Reading device database...$COFF"
 DBF2=$(mktemp); DBF_ACPI=$(mktemp); DBF_PCI=$(mktemp)
 DBF_HDAUDIO=$(mktemp); DBF_USB=$(mktemp)
-grep -e "$WIN" "$DBFILE" > $DBF2
+if ! grep -e "$WIN" "$DBFILE" > $DBF2 2>/dev/null
+	then echo -e "\n${CRED}Error reading $CWHT$DBFILE$COFF"
+	exit 1
+fi
 DBFILE="$DBF2"
 grep -e '^acpi:' "$DBF2" > $DBF_ACPI
 grep -e '^pci:' "$DBF2" > $DBF_PCI
