tt_driverdrop: don't check Windows INFs unless asked

diff --git a/scripts/tt_driverdrop b/scripts/tt_driverdrop
--- a/scripts/tt_driverdrop
+++ b/scripts/tt_driverdrop
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-VER=0.8.2
-VERDATE=2016-10-20
+VER=0.8.3
+VERDATE=2017-06-01
 
 BLACKLIST=" acpi:dev=pnp0103 acpi:dev=pnp0300 acpi:dev=pnp0301 acpi:dev=pnp0302 acpi:dev=pnp0303 acpi:dev=pnp0a03 acpi:dev=pnp0a08 acpi:dev=pnp0c0f acpi:dev=pnp0f13 acpi:dev=abcd0001 acpi:dev=int3f0d"
 
@@ -95,6 +95,7 @@ get_host_winver_flags () {
 
 test "$1" = "simulate" && SIMULATE=1
 DBG=0; test "$1" = "-d" && DBG=1; test "$1" = "-dd" && DBG=2
+WINDB=0; test "$1" = "-w" && WINDB=1
 if [[ $DBG -eq 0 && "$1" != "dump" ]]
 	then TMP=$(mktemp)
 	tt__disk_prompt $TMP
@@ -102,9 +103,10 @@ if [[ $DBG -eq 0 && "$1" != "dump" ]]
 	rm $TMP
 
 	PART="$(cat /proc/partitions | awk '{ print $3" "$4 }' | \
-		grep $DEV\[1-9\] | sort -gr | \
+		grep "${DEV}p*[0-9]" | sort -gr | \
 		awk '{ print $2 }' | tr \\n ' ')"
 	PART="$(echo $PART | tr ' ' \\n | head -n 1)"
+	test -z "$PART" && echo "Could not find partitions for device. Aborting." && exit 1
 	echo "${CWHT}Using $CGRN/mnt/$PART$CWHT as hard drive$COFF"
 
 	EXIST="$(grep "/dev/$PART" /proc/mounts | head -n 1 | awk '{ print $2 }')"
@@ -202,7 +204,7 @@ if [ "$1" = "dump" ]
 	else
 	get_host_winver_flags
 	BDDB="-q"; test $DBG -gt 0 && unset BDDB
-	test -d "$MTPT/$INFDIR" && DRVROOT="$MTPT/$INFDIR" tt_build_dev_db $BDDB
+	test "$WINDB" = "1" && test -d "$MTPT/$INFDIR" && DRVROOT="$MTPT/$INFDIR" tt_build_dev_db $BDDB
 fi
 
 # Make temporary versions of the DB with incompatible entries stripped
@@ -286,59 +288,61 @@ done
 
 DIRS="$(echo "$DIRS" | tr ' ' \\n | grep -v '^$' | sort | uniq)"
 
-echo "${CWHT}Checking if missing drivers are covered by Windows...$COFF"
-DBFILE=$INFDIR/devicedb.txt
-for X in $NODRV
-	do TYPE=$(echo "$X" | cut -d: -f1)
-	if [ "$TYPE" = "hdaudio" ]
-		then echo "$X"
-		printf "%-74s" "                        "
-		else printf "%-74s" "$X     "
-	fi
-	R=0
-	unset USE TDV REQ1 REQ2
-	TAGS=$(echo "$X" | cut -d: -f2- | tr ':' ' ')
-	case $TYPE in
-		pci|hdaudio)
-			REQ1="$(echo "$X" | sed 's/.*:\(ven=....\).*/\1/')"
-			REQ2="$(echo "$X" | sed 's/.*:\(dev=....\).*/\1/')"
-			CCREQ="$(echo "$X" | sed 's/.*:\(cc=....\).*/\1/')"
-			TAGS="$(echo "$TAGS" | sed 's/ven=....//;s/dev=....//')"
-			grep "^$TYPE" "$DBFILE" | grep "$REQ1" | grep "$REQ2" > $TF
-			# Sometimes a class specifier matches the device instead.
-			grep "^$TYPE" "$DBFILE" | grep "$CCREQ" >> $TF
-			test ! -z "$(cat $TF)" && R=1
-			;;
-		usb)
-			grep "^$TYPE" "$DBFILE" > $TF
-			;;
-		acpi)
-			grep "^$X" "$DBFILE" > $TF
-			;;
-
-	esac
-	while read LINE
-		do
-		rotate_progress
-		for TAG in $TAGS
-			do echo "$LINE" | grep -q "$TAG" && R=1
-		done
-
-		if [ "$R" = "1" ]
-			then
-			NODRV="$(echo "$NODRV" | tr ' ' \\n | grep -v "$X" | tr \\n ' ' | sed 's/  / /g')"
-			test $DBG -gt 1 && echo -e "\n${CGRN}Using $LINE$COFF"
-			test $DBG -le 1 && echo -e "\b [${CGRN}OK${COFF}]"
-			break
+if [ "$WINDB" = "1" ]
+	then
+	echo "${CWHT}Checking if missing drivers are covered by Windows...$COFF"
+	DBFILE=$INFDIR/devicedb.txt
+	for X in $NODRV
+		do TYPE=$(echo "$X" | cut -d: -f1)
+		if [ "$TYPE" = "hdaudio" ]
+			then echo "$X"
+			printf "%-74s" "                        "
+			else printf "%-74s" "$X     "
 		fi
-	done < $TF
-	if [ "$R" = "0" ]
-		then
-		test $DBG -gt 1 && echo -e "\n${CRED}No driver found for $X$COFF"
-		test $DBG -le 1 && echo "[${CYEL}!!${COFF}]"
-	fi
-done
+		R=0
+		unset USE TDV REQ1 REQ2
+		TAGS=$(echo "$X" | cut -d: -f2- | tr ':' ' ')
+		case $TYPE in
+			pci|hdaudio)
+				REQ1="$(echo "$X" | sed 's/.*:\(ven=....\).*/\1/')"
+				REQ2="$(echo "$X" | sed 's/.*:\(dev=....\).*/\1/')"
+				CCREQ="$(echo "$X" | sed 's/.*:\(cc=....\).*/\1/')"
+				TAGS="$(echo "$TAGS" | sed 's/ven=....//;s/dev=....//')"
+				grep "^$TYPE" "$DBFILE" | grep "$REQ1" | grep "$REQ2" > $TF
+				# Sometimes a class specifier matches the device instead.
+				grep "^$TYPE" "$DBFILE" | grep "$CCREQ" >> $TF
+				test ! -z "$(cat $TF)" && R=1
+				;;
+			usb)
+				grep "^$TYPE" "$DBFILE" > $TF
+				;;
+			acpi)
+				grep "^$X" "$DBFILE" > $TF
+				;;
 
+		esac
+		while read LINE
+			do
+			rotate_progress
+			for TAG in $TAGS
+				do echo "$LINE" | grep -q "$TAG" && R=1
+			done
+
+			if [ "$R" = "1" ]
+				then
+				NODRV="$(echo "$NODRV" | tr ' ' \\n | grep -v "$X" | tr \\n ' ' | sed 's/  / /g')"
+				test $DBG -gt 1 && echo -e "\n${CGRN}Using $LINE$COFF"
+				test $DBG -le 1 && echo -e "\b [${CGRN}OK${COFF}]"
+				break
+			fi
+		done < $TF
+		if [ "$R" = "0" ]
+			then
+			test $DBG -gt 1 && echo -e "\n${CRED}No driver found for $X$COFF"
+			test $DBG -le 1 && echo "[${CYEL}!!${COFF}]"
+		fi
+	done
+fi
 if [[ $DBG -gt 1 || -n $SIMULATE ]]
 	then echo -e "DIRS: \n$(echo "$DIRS" | tr ' ' \\n)"
 	exit
