Speed up driverdrop, use faster lzop, enhance backup utility

diff --git a/scripts/tt_driverdrop b/scripts/tt_driverdrop
--- a/scripts/tt_driverdrop
+++ b/scripts/tt_driverdrop
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-VER=0.4
-VERDATE=2014-07-25
+VER=0.3.1
+VERDATE=2015-01-14
 
 BLACKLIST=" acpi:dev=pnp0103 acpi:dev=pnp0a03 acpi:dev=pnp0a08 acpi:dev=pnp0c0f"
 
@@ -20,6 +20,9 @@ clean_exit () {
 trap clean_exit INT ABRT TERM HUP
 
 if ! lspci 2>&1 >/dev/null; then echo "${CRED}lspci does not work, aborting.$COFF"; clean_exit 1; fi
+if ! dmidecode 2>&1 >/dev/null; then echo "${CRED}dmidecode does not work, aborting.$COFF"; clean_exit 1; fi
+
+BIOSDATE="$(dmidecode -t bios | grep Release | sed 's#.*/##' | grep '[0-9][0-9][0-9][0-9]')"
 
 test -z "$DRIVERS" && DRIVERS="$SOURCE/drivers"
 test -z "$DBFILE" && DBFILE="$DRIVERS/devicedb.txt"
@@ -34,10 +37,6 @@ if grep -q "^/mnt/cifs" "$DBFILE"
 	cat "$DBFILE" > $DBF2
 	DBFILE="$DBF2"
 fi
-
-# Get DB version number
-DBVER="$(grep -m 1 '^tritech_devdb_ver:' $DBFILE | cut -d: -f2)"
-test -z "$DBVER" && echo "Bad database version in $DBFILE" && clean_exit 1
 
 ### Functions
 
@@ -62,18 +61,16 @@ get_host_winver_flags () {
 	INFDIR=__NONE__; for X in inf Inf INF; do test -d $WINDIR/$X && INFDIR=$WINDIR/$X; done
 	WINDBFILE=$INFDIR/devicedb.txt
 	WINVER=$(tt_winver)
-	W2K=.; XP32=.; V32=.; W732=.; W832=.; W8132=.
+	W2K=.; XP32=.; V32=.; W732=.; W832=.
 	IA64=.; S2K3=.; S2K364=.
-	XP64=.; V64=.; W764=.; W864=.; W8164=.
+	XP64=.; V64=.; W764=.; W864=.
 	case $WINVER in
 		ntia64*) IA64=1 ;;
-		ntamd64.6.3) W8164=1 ;;
 		ntamd64.6.2) W864=1 ;;
 		ntamd64.6.1) W764=1 ;;
 		ntamd64.6.0) V64=1 ;;
 		ntamd64.5.2) S2K364=1 ;;
 		ntamd64.5.1) XP64=1 ;;
-		ntx86.6.3) W8132=1 ;;
 		ntx86.6.2) W832=1 ;;
 		ntx86.6.1) W732=1 ;;
 		ntx86.6.0) V32=1 ;;
@@ -82,17 +79,7 @@ get_host_winver_flags () {
 		ntx86.5.0) W2K=1 ;;
 		*) echo "tt_winver failed!"; exit 1 ;;
 	esac
-	WF=":win=$IA64$W2K$XP32$XP64$S2K3$S2K364$V32$V64$W732$W764$W832$W864"
-	if [ "$DBVER" = "001" ]
-		then echo "$WINVER" | grep -q 'nt[^.]*\.6\.3' && \
-			echo "Master device DB version too old for this OS" && \
-			clean_exit 1
-	fi
-	test "$DBVER" = "002" && WF=":win=$IA64$W2K$XP32$XP64$S2K3$S2K364$V32$V64$W732$W764$W832$W864$W8132$W8164"
-	if ! echo "$TF" | grep -q '1'
-		then echo "No Windows version flags set, aborting."
-		clean_exit 1
-	fi
+	WIN=":win=$IA64$W2K$XP32$XP64$S2K3$S2K364$V32$V64$W732$W764$W832$W864"
 }
 
 ### End functions
@@ -140,7 +127,7 @@ for X in $(lspci -mmn | tr -d ' ')
 	CC=":cc=$(echo "$X" | cut -d\" -f2)"
 	VEN=":ven=$(echo "$X" | cut -d\" -f4)"
 	DEV=":dev=$(echo "$X" | cut -d\" -f6)"
-	test ! -z "$(echo "$X" | cut -d\" -f8)" && SUBSYS=":subsys=$(echo "$X" | cut -d\" -f8,10 | tr -d \" | sed 's/\(....\)\(....\)/\2\1/')"
+	test ! -z "$(echo "$X" | cut -d\" -f8)" && SUBSYS=":subsys=$(echo "$X" | cut -d\" -f8,10 | tr -d \" )"
 	test ! -z "$(echo "$X" | cut -d\" -f7 | sed 's/-p..//')" && REV=":rev=$(echo "$X" | cut -d\" -f7 | sed 's/-p..//;s/-r//')"
 	THISDEV="$TYPE$FUNC$CC$CV$CD$VID$PID$VEN$DEV$SUBSYS$REV$CLASS$SC$PROT"
 	echo "$BLACKLIST" | grep -q " $THISDEV" || DEVS="$DEVS $THISDEV"
@@ -171,6 +158,7 @@ echo -n "${CGRN}HDAUDIO $COFF"; TYPE="hdaudio"
 for X in /proc/asound/card*/codec#*
 	do
 	unset FUNC CC CV CD VID PID VEN DEV SUBSYS REV CLASS SC PROT THISDEV
+	SCORE=0; BEST=0; DV=0
 	CARD="$(echo "$X" | cut -d/ -f4)"
 	FUNC=":func=02"; grep -iq 'No Modem Function Group' $X && FUNC=":func=01"
 	CV=":cv=$(cut -dx -f2 < /sys/class/sound/$CARD/device/vendor)"
@@ -202,24 +190,24 @@ for X in $DEVS
 	TAGS=$(echo "$X" | cut -d: -f2- | tr ':' ' ')
 	case $TYPE in
 		pci|hdaudio)
-			VEN="$(echo "$X" | sed 's/.*\(ven=....\).*/\1/')"
-			DEV="$(echo "$X" | sed 's/.*\(dev=....\).*/\1/')"
-			SUBSYS="$(echo "$X" | sed 's/.*\(subsys=........\).*/\1/')"
+			VEN="$(echo "$X" | sed 's/.*\(:ven=....:\).*/\1/')"
+			DEV="$(echo "$X" | sed 's/.*\(:dev=....:\).*/\1/')"
+			SUBSYS="$(echo "$X" | sed 's/.*\(:subsys=........\).*/\1/')"
 			TAGS="$(echo "$TAGS" | sed 's/ven=....//;s/dev=....//')"
-			test $DBG -gt 1 && echo "$TYPE VEN $VEN, DEV $DEV, SUBSYS $SUBSYS, TAGS $TAGS"
-			grep "^$TYPE:$VEN:$DEV" "$DBFILE" | grep "$WF" > $TF
+			grep "$SUBSYS" "$DBFILE" | grep "$VEN" | grep "$DEV" | grep "^$TYPE" | grep "$WIN" > $TF
+			test -z "$(cat $TF)" && grep "$DEV" "$DBFILE" | grep "$WIN" | grep "$VEN" | grep "^$TYPE" > $TF
 			;;
 		usb)
 			CLASS="$(echo "$X" | sed 's/.*\(:class=..\).*/\1/')"
 			SC="$(echo "$X" | sed 's/.*\(:sc=..\).*/\1/')"
 			PROT="$(echo "$X" | sed 's/.*\(:prot=..\).*/\1/')"
 			VID="$(echo "$X" | sed 's/.*\(:vid=....\).*/\1/')"
-			grep "$CLASS" "$DBFILE" | grep "^$TYPE" | grep "$WF" | grep "$SC" | grep "$PROT" > $TF
-			test -z "$(cat $TF)" && grep "^$TYPE" "$DBFILE" | grep "$WF" | grep "$VID" > $TF
+			grep "$CLASS" "$DBFILE" | grep "^$TYPE" | grep "$WIN" | grep "$SC" | grep "$PROT" > $TF
+			test -z "$(cat $TF)" && grep "^$TYPE" "$DBFILE" | grep "$WIN" | grep "$VID" > $TF
 			;;
 		acpi)
 			REQ1="$(echo "$X" | sed 's/.*\(:dev=.*:\).*/\1/')"
-			grep "^$TYPE" "$DBFILE" | grep "$WF" | grep "$REQ1" > $TF
+			grep "^$TYPE" "$DBFILE" | grep "$WIN" | grep "$REQ1" > $TF
 			;;
 
 	esac
