driverdrop: Win8.1 support, OS flag fixes, SUBSYS order bug fix

diff --git a/scripts/tt_driverdrop b/scripts/tt_driverdrop
--- a/scripts/tt_driverdrop
+++ b/scripts/tt_driverdrop
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-VER=0.3
-VERDATE=2014-01-17
+VER=0.4
+VERDATE=2014-07-25
 
 BLACKLIST=" acpi:dev=pnp0103 acpi:dev=pnp0a03 acpi:dev=pnp0a08 acpi:dev=pnp0c0f"
 
@@ -35,6 +35,10 @@ if grep -q "^/mnt/cifs" "$DBFILE"
 	DBFILE="$DBF2"
 fi
 
+# Get DB version number
+DBVER="$(grep -m 1 '^tritech_devdb_ver:' $DBFILE | cut -d: -f2)"
+test -z "$DBVER" && echo "Bad database version in $DBFILE" && clean_exit 1
+
 ### Functions
 
 ROTATE=0
@@ -58,16 +62,18 @@ get_host_winver_flags () {
 	INFDIR=__NONE__; for X in inf Inf INF; do test -d $WINDIR/$X && INFDIR=$WINDIR/$X; done
 	WINDBFILE=$INFDIR/devicedb.txt
 	WINVER=$(tt_winver)
-	W2K=.; XP32=.; V32=.; W732=.; W832=.
+	W2K=.; XP32=.; V32=.; W732=.; W832=.; W8132=.
 	IA64=.; S2K3=.; S2K364=.
-	XP64=.; V64=.; W764=.; W864=.
+	XP64=.; V64=.; W764=.; W864=.; W8164=.
 	case $WINVER in
 		ntia64*) IA64=1 ;;
+		ntamd64.6.3) W8164=1 ;;
 		ntamd64.6.2) W864=1 ;;
 		ntamd64.6.1) W764=1 ;;
 		ntamd64.6.0) V64=1 ;;
 		ntamd64.5.2) S2K364=1 ;;
 		ntamd64.5.1) XP64=1 ;;
+		ntx86.6.3) W8132=1 ;;
 		ntx86.6.2) W832=1 ;;
 		ntx86.6.1) W732=1 ;;
 		ntx86.6.0) V32=1 ;;
@@ -76,7 +82,17 @@ get_host_winver_flags () {
 		ntx86.5.0) W2K=1 ;;
 		*) echo "tt_winver failed!"; exit 1 ;;
 	esac
-	WIN=":win=$IA64$W2K$XP32$XP64$S2K3$S2K364$V32$V64$W732$W764$W832$W864"
+	WF=":win=$IA64$W2K$XP32$XP64$S2K3$S2K364$V32$V64$W732$W764$W832$W864"
+	if [ "$DBVER" = "001" ]
+		then echo "$WINVER" | grep -q 'nt[^.]*\.6\.3' && \
+			echo "Master device DB version too old for this OS" && \
+			clean_exit 1
+	fi
+	test "$DBVER" = "002" && WF=":win=$IA64$W2K$XP32$XP64$S2K3$S2K364$V32$V64$W732$W764$W832$W864$W8132$W8164"
+	if ! echo "$TF" | grep -q '1'
+		then echo "No Windows version flags set, aborting."
+		clean_exit 1
+	fi
 }
 
 ### End functions
@@ -124,7 +140,7 @@ for X in $(lspci -mmn | tr -d ' ')
 	CC=":cc=$(echo "$X" | cut -d\" -f2)"
 	VEN=":ven=$(echo "$X" | cut -d\" -f4)"
 	DEV=":dev=$(echo "$X" | cut -d\" -f6)"
-	test ! -z "$(echo "$X" | cut -d\" -f8)" && SUBSYS=":subsys=$(echo "$X" | cut -d\" -f8,10 | tr -d \" )"
+	test ! -z "$(echo "$X" | cut -d\" -f8)" && SUBSYS=":subsys=$(echo "$X" | cut -d\" -f8,10 | tr -d \" | sed 's/\(....\)\(....\)/\2\1/')"
 	test ! -z "$(echo "$X" | cut -d\" -f7 | sed 's/-p..//')" && REV=":rev=$(echo "$X" | cut -d\" -f7 | sed 's/-p..//;s/-r//')"
 	THISDEV="$TYPE$FUNC$CC$CV$CD$VID$PID$VEN$DEV$SUBSYS$REV$CLASS$SC$PROT"
 	echo "$BLACKLIST" | grep -q " $THISDEV" || DEVS="$DEVS $THISDEV"
@@ -187,24 +203,24 @@ for X in $DEVS
 	TAGS=$(echo "$X" | cut -d: -f2- | tr ':' ' ')
 	case $TYPE in
 		pci|hdaudio)
-			VEN="$(echo "$X" | sed 's/.*\(:ven=....:\).*/\1/')"
-			DEV="$(echo "$X" | sed 's/.*\(:dev=....:\).*/\1/')"
-			SUBSYS="$(echo "$X" | sed 's/.*\(:subsys=........\).*/\1/')"
+			VEN="$(echo "$X" | sed 's/.*\(ven=....\).*/\1/')"
+			DEV="$(echo "$X" | sed 's/.*\(dev=....\).*/\1/')"
+			SUBSYS="$(echo "$X" | sed 's/.*\(subsys=........\).*/\1/')"
 			TAGS="$(echo "$TAGS" | sed 's/ven=....//;s/dev=....//')"
-			grep "$SUBSYS" "$DBFILE" | grep "$VEN" | grep "$DEV" | grep "^$TYPE" | grep "$WIN" > $TF
-			test -z "$(cat $TF)" && grep "^$TYPE" "$DBFILE" | grep "$WIN" | grep "$VEN" | grep "$DEV" > $TF
+			test $DBG -gt 1 && echo "$TYPE VEN $VEN, DEV $DEV, SUBSYS $SUBSYS, TAGS $TAGS"
+			grep "^$TYPE:$VEN:$DEV" "$DBFILE" | grep "$WF" > $TF
 			;;
 		usb)
 			CLASS="$(echo "$X" | sed 's/.*\(:class=..\).*/\1/')"
 			SC="$(echo "$X" | sed 's/.*\(:sc=..\).*/\1/')"
 			PROT="$(echo "$X" | sed 's/.*\(:prot=..\).*/\1/')"
 			VID="$(echo "$X" | sed 's/.*\(:vid=....\).*/\1/')"
-			grep "$CLASS" "$DBFILE" | grep "^$TYPE" | grep "$WIN" | grep "$SC" | grep "$PROT" > $TF
-			test -z "$(cat $TF)" && grep "^$TYPE" "$DBFILE" | grep "$WIN" | grep "$VID" > $TF
+			grep "$CLASS" "$DBFILE" | grep "^$TYPE" | grep "$WF" | grep "$SC" | grep "$PROT" > $TF
+			test -z "$(cat $TF)" && grep "^$TYPE" "$DBFILE" | grep "$WF" | grep "$VID" > $TF
 			;;
 		acpi)
 			REQ1="$(echo "$X" | sed 's/.*\(:dev=.*:\).*/\1/')"
-			grep "^$TYPE" "$DBFILE" | grep "$WIN" | grep "$REQ1" > $TF
+			grep "^$TYPE" "$DBFILE" | grep "$WF" | grep "$REQ1" > $TF
 			;;
 
 	esac
