tt_imagedrop: add a capacity sanity check

diff --git a/scripts/tt_imagedrop b/scripts/tt_imagedrop
--- a/scripts/tt_imagedrop
+++ b/scripts/tt_imagedrop
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-VER="2.1.1"
-VERDATE="2016-09-20"
+VER="2.2"
+VERDATE="2016-10-02"
 
 shopt -s nullglob
 . tss__common
@@ -170,6 +170,23 @@ if [ $UEFI -eq 0 ]
 	CYLS=$(expr $BLOCKS / $HEADS / 63)
 	echo "$DEV: ${HEADS}/${XHEADS} heads, $CYLS cylinders, 63 sectors."
 fi
+
+# Do a rough capacity sanity check
+DESTSIZE=$(stat -c %s "$IMG")
+DESTSIZE=$((DESTSIZE * 24))
+DESTSIZE=$((DESTSIZE / 10))
+DEVBYTES=$(BLOCKS / 512)
+if [ $DESTSIZE -ge $DEVBYTES ]
+	then echo "${CYEL}===== WARNING =====$COFF"
+	echo "${CWHT}$DEV$CYEL may not be large enough for this image$COFF"
+	echo -n "${CYEL}Are you sure that you want to continue (y/N)? $COFF"
+	read -n 1 X
+	if [[ $X != "n" && $X != "N" ]]
+		then echo "${CRED}Aborting due to insufficient device capacity.$COFF"
+		exit 1
+	fi
+fi
+
 check_mounts
 
 # Use sgdisk to destroy GPT backup sectors, then drop an image
