tt_sysupdate: reject invalid selections better

diff --git a/scripts/tt_sysupdate b/scripts/tt_sysupdate
--- a/scripts/tt_sysupdate
+++ b/scripts/tt_sysupdate
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-VER=1.6.1
-VERDATE="2017-08-19"
+VER=1.6.2
+VERDATE="2017-11-01"
 
 . tss__common
 
@@ -228,10 +228,10 @@ if [ "$I" -gt "1" ]
 		then echo "User canceled update process."
 		exit 1
 	fi
-	X=$(echo $X | sed 's/[^0-9]//g')
-	if [[ $X -lt 0 || $X -gt $I ]]
-		then USE=0
-		else USE=$X
+	USE=$(echo $X | sed 's/[^0-9]//g')
+	if [[ -z "$USE" || $USE -lt 0 || $USE -ge $I ]]
+		then echo "Aborting: invalid selection given"
+		exit 1
 	fi
 fi
 
