tt_winver: use winregfs when possible, fall back on failure

diff --git a/scripts/tt_winver b/scripts/tt_winver
--- a/scripts/tt_winver
+++ b/scripts/tt_winver
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-VER=0.2
-VERDATE=2013-12-06
+VER=0.3
+VERDATE=2014-05-28
 
 test -z "$TSS_COMMON" && . tss__common
 test -z "$TSS_COMMON" && echo "tss__common required but failed to load." && exit 1
@@ -18,16 +18,42 @@ for X in $WINDIR/$SYS32/PRODSPEC.INI $WINDIR/$SYS32/prodspec.ini $WINDIR/$SYS32/
 done
 test "$REGSW" = "__NONE__" && echo "Cannot find SOFTWARE hive." && exit 3
 
-TMP=$(mktemp)
-
-reged -x "$REGSW" SOFTWARE 'Microsoft\Windows NT\CurrentVersion' $TMP >/dev/null
-sed -i 's/\\CMI-CreateHive{29EE1162-53C9-4474-A2B6-D90A7F6B0A7C}//g' $TMP
-CVER="$(read_inf_section $TMP 'SOFTWARE\Microsoft\Windows NT\CurrentVersion' | grep -i '"CurrentVersion"=' | cut -d\" -f4)"
-PNAME="$(read_inf_section $TMP 'SOFTWARE\Microsoft\Windows NT\CurrentVersion' | grep -i '"ProductName"=' | cut -d\" -f4)"
-if [ $(echo "$CVER" | cut -d. -f1) -lt 6 ]
-	then EDITION="$(read_inf_section $PRODSPEC "Product Specification" | grep 'Product=' | cut -d' ' -f3- | tr -d \\n | tr -d \\r)"
-	else EDITION="$(read_inf_section $TMP 'SOFTWARE\Microsoft\Windows NT\CurrentVersion' | grep -i '"EditionID"=' | cut -d\" -f4)"
+if mount.winregfs -v 2>/dev/null
+	then
+	# Use winregfs to read registry data
+	TMP=$(mktemp -d || echo "/tmp/foo")
+	if ! mount.winregfs "$REGSW" $TMP 2>/dev/null
+		then echo "error: cannot mount $REGSW"
+		fusermount -u $TMP 2>/dev/null
+		rmdir -f $TMP
+		exit 1
+	fi
+	CVER="$(cat "$TMP/Microsoft/Windows NT/CurrentVersion/CurrentVersion.sz")"
+	PNAME="$(cat "$TMP/Microsoft/Windows NT/CurrentVersion/ProductName.sz")"
+	if [ $(echo "$CVER" | cut -d. -f1) -lt 6 ]
+		then EDITION="$(read_inf_section $PRODSPEC "Product Specification" | grep 'Product=' | cut -d' ' -f3- | tr -d \\n | tr -d \\r)"
+		else EDITION="$(cat "$TMP/Microsoft/Windows NT/CurrentVersion/EditionID.sz")"
+	fi
+	fusermount -u $TMP
+	rm -rf $TMP
 fi
+
+# Fall back to the "old way" if anything went wrong
+if [ -z "$CVER" ]
+	then
+	# Use chntpw's reged to read registry data (slower)
+	TMP=$(mktemp)
+	reged -x "$REGSW" SOFTWARE 'Microsoft\Windows NT\CurrentVersion' $TMP >/dev/null
+	sed -i 's/\\CMI-CreateHive{29EE1162-53C9-4474-A2B6-D90A7F6B0A7C}//g' $TMP
+	CVER="$(read_inf_section $TMP 'SOFTWARE\Microsoft\Windows NT\CurrentVersion' | grep -i '"CurrentVersion"=' | cut -d\" -f4)"
+	PNAME="$(read_inf_section $TMP 'SOFTWARE\Microsoft\Windows NT\CurrentVersion' | grep -i '"ProductName"=' | cut -d\" -f4)"
+	if [ $(echo "$CVER" | cut -d. -f1) -lt 6 ]
+		then EDITION="$(read_inf_section $PRODSPEC "Product Specification" | grep 'Product=' | cut -d' ' -f3- | tr -d \\n | tr -d \\r)"
+		else EDITION="$(read_inf_section $TMP 'SOFTWARE\Microsoft\Windows NT\CurrentVersion' | grep -i '"EditionID"=' | cut -d\" -f4)"
+	fi
+	rm -f $TMP
+fi
+
 if [ "$SYS64" = "__NONE__" ]
 	then WINARCH="ntx86"
 	else WINARCH="ntamd64"
@@ -40,4 +66,3 @@ if [ "$1" = "-a" ]
 	else echo "$WINVER"
 fi
 
-rm -f $TMP
